# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Amazon-EC2-Metadata
version:      0.10
version_from: lib/Net/Amazon/EC2/Metadata.pm
installdirs:  site
requires:
    LWP::Simple:                   0
    Perl6::Say:                    0
    Pod::Usage:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
